spring:
  jackson:
    serialization:
      WRITE_CHAR_ARRAYS_AS_JSON_ARRAYS: false
  data:
    rest:
      basePath: /api
      defaultMediaType: application/hal+json
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
logging:
  level:
    be.ordina: 'DEBUG'
    org.hibernate: 'ERROR'
config:
  retry:
    initialInterval: 2000
    multiplier: 1.2
    maxInterval: 100000
    maxAttempts: 20